### TO DO ###




# version: '3.9'

# services:
#   nodejs-app:
#     build:
#       context: .
#       target: run
#     image: tivix-nodejs-task
#     env_file:
#       - .env
#     ports:
#       - target: 3000
#         published: 3000
#         protocol: tcp
#         mode: host
#     depends_on:
#       - postgres_db
#   postgres_db:
#     image: postgres
#     volumes:
#       - postgres_db_data:/data
#     ports:
#       - target: 5432
#         published: 5432
#         protocol: tcp
#         mode: host
#     env_file:
#       - postgres.env
    
# volumes:
#   postgres_db_data: